name: Build NAStool Enhanced Image Dev

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set Up Build
        uses: docker/setup-buildx-action@v1

      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate release tag
        id: tag
        run: |
          echo "release_tag=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/dev.dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools-enhanced:test